theme: jekyll-theme-cayman
title: COVID-19 facts and updates
subtitle: Current and succinct COVID-19 facts and info for South Africans
author: Craig Feldman
github:
  is_project_page: false
google_analytics: G-JLRD7K9KSL
